
name: basic test
on: 
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]
jobs:
    job1:
        name: test
        runs-on: ubuntu-latest
        steps:
            - name: test uname -a
            env:
                UNAME: "uname -a"
            - run: echo $UNAME
    job2:
        name: test
        runs-on: windows-latest
        steps:
            - run: python --version
