
name: basic test
on: 
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]
jobs:
    job1:
        name: ubuntu test
        env:
            UNAME: uname -a
            USER: "tlc"
        runs-on: ubuntu-latest
        steps:
        - run: echo $($UNAME)
        - run: echo $USER
    job2:
        name: windows test
        runs-on: windows-latest
        steps:
            - run: python --version
